resize: adding window resize for cameras
mmphego/face_mask_detection_openvino pull request #4
Opened 2021-02-05 15:35 UTC by munoz0raul

2021-02-06 03:44 UTC, mmphego requested changes
Thanks for the change req.
Just minor recommendations and we are good to go.

2021-02-06 03:44 UTC, mmphego commented on main.py
> +import cv2
`cv2` forms part of `pyvino_utils` so we do not need to import it here.

https://github.com/B0N0AI/pyvino_utils/blob/master/pyvino_utils/input_handler/input_feeder.py#L4
```suggestion
```

2021-02-06 03:44 UTC, mmphego commented on main.py
> +    )
:+1:

2021-02-06 03:44 UTC, mmphego commented on main.py
> +    input_feed.cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)
Perhaps, use the method that forms part of the `InputFeeder` class.
https://github.com/B0N0AI/pyvino_utils/blob/master/pyvino_utils/input_handler/input_feeder.py#L114+L119
```suggestion
input_feed.resize_cam_input(args.height, args.width)
```

2021-02-16 11:30 UTC, munoz0raul commented
Hi @mmphego, I updated the commit with all changes you request. 

Raul.

2021-02-16 12:18 UTC, mmphego commented
@munoz0raul Did you have time to test these changes?
I will merge this PR.

2021-02-16 12:18 UTC, merged